backend:
  name: github
  repo: stephanie-flower/animesoc-website
  branch: next-js
  base_url: http://localhost:8000
  auth_endpoint: /cms/auth
media_folder: npm-new/anisoc/public/images
public_folder: images
collections:
  - name: "events"
    label: "Events"
    extension: "json"
    editor:
      preview: false

    files:
      - file: "npm-new/anisoc/components/data/events.json"
        label: "Events Section"
        name: "events"
        fields:
          - label: "Events"
            name: "eventList"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: string }
              - {
                  label: "Date",
                  name: "date",
                  widget: datetime,
                  default: "",
                  date_format: "DD/MM/YYYY",
                  time_format: "HH:mm",
                  format: "DD/MM/YYYY HH:mm",
                }
              - { label: "Location", name: "location", widget: string }
              - { label: "Description", name: "description", widget: text }
              - { label: "Image", name: "image", widget: image }
