# Generated by Django 3.1.5 on 2021-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Untitled_Event', max_length=200, verbose_name='Event name'),
        ),
    ]
