# Generated by Django 3.1.5 on 2021-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_time', models.DateTimeField(verbose_name='Time')),
                ('show_event', models.BooleanField(default=False)),
                ('event_location', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
